services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    tty: true
    stdin_open: true
    build: .
    command: sh /usr/bin/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      OAUTH_PROVIDER_URL: http://localhost:3000
      OAUTH_CLIENT_ID: 6w43jHSJ1c619BLW-KdDO_9KLNchvoyEizV60Efei1w
      OAUTH_CLIENT_SECRET: 0fhV6TYf_7BpvLcOOt61rWDSjY7V_2-dyWnOWeaJXBU
