services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    tty: true
    stdin_open: true
    build: .
    command: sh /usr/bin/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
